# nginx proxy address - http://172.17.0.1:8090

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  drawio:
    image: jgraph/drawio:latest
    container_name: drawio-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - drawio
    ports:
      - "8090:8080"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./rootfs/config/drawio:/config
      - ./rootfs/data/drawio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  drawio:
    external: false
